"""Utilities to visualise class distributions for CIFAR-10 LDA partitions.

This module provides a small command line interface that inspects a partition
folder produced by :func:`project.task.utils.common.create_lda_partitions` and
creates a heatmap summarising the client/class distribution.  The default
configuration targets the partition generated by
``data/CIFAR10/lda_0.5_10`` (10 clients with :math:`\alpha=0.5`).  The script
expects each client directory to contain a ``train.pt`` (and optionally a
``test.pt``) file with a mapping ``{"data": Tensor, "targets": Tensor}`` as
stored by the dataset preparation utilities in this repository.

Example
-------
```
python plotting/plots/cifar_lda_partition_plot.py \
    --partition-dir data/CIFAR10/lda_0.5_10 \
    --output plotting/plots/data/cifar10_lda_0.5_10.png
```
"""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Iterable, Sequence

import matplotlib
import matplotlib.pyplot as plt
import numpy as np
import torch

# Use a non-interactive backend so that the script can be executed in headless
# environments (e.g. CI, remote servers).
matplotlib.use("Agg")


def _load_targets(file_path: Path) -> np.ndarray:
    """Return the target labels stored in ``file_path`` as a NumPy array."""

    dataset = torch.load(file_path)
    targets = dataset["targets"]

    if isinstance(targets, torch.Tensor):
        targets = targets.detach().cpu().numpy()
    else:
        targets = np.asarray(targets)

    if targets.ndim != 1:
        msg = (
            f"Expected 1-D targets in {file_path!s},"
            f" but received array with shape {targets.shape}."
        )
        raise ValueError(msg)

    return targets.astype(int, copy=False)


def _iter_client_dirs(partition_dir: Path) -> Iterable[Path]:
    """Yield client directories sorted by their numeric identifier."""

    def _client_key(client_path: Path) -> int:
        try:
            return int(client_path.name.split("_")[-1])
        except ValueError as exc:  # pragma: no cover - defensive programming
            raise ValueError(
                "Client directories must be named following the pattern "
                "'client_<index>'"
            ) from exc

    return sorted(
        [path for path in partition_dir.iterdir() if path.is_dir()],
        key=_client_key,
    )


def load_class_counts(
    partition_dir: Path,
    *,
    split: str = "train",
    num_classes: int | None = None,
) -> tuple[Sequence[str], np.ndarray]:
    """Load the class counts for each client contained in ``partition_dir``.

    Parameters
    ----------
    partition_dir:
        Directory that stores the federated partitions.  Each client is expected
        to have a sub-directory named ``client_<index>`` containing a
        ``{split}.pt`` file.
    split:
        Dataset split to inspect (``"train"`` or ``"test"``).  Defaults to
        ``"train"``.
    num_classes:
        If provided, ensure that the resulting count matrix has ``num_classes``
        columns.  When omitted, the number of columns is inferred from the
        largest label encountered.

    Returns
    -------
    Sequence[str]
        Client identifiers sorted by index.
    numpy.ndarray
        Matrix of shape ``(num_clients, num_classes)`` with the class counts.
    """

    split_file = f"{split}.pt"
    client_dirs = _iter_client_dirs(partition_dir)

    if not client_dirs:
        raise FileNotFoundError(
            f"No client directories found inside {partition_dir!s}."
        )

    counts: list[np.ndarray] = []
    max_label = -1

    for client_dir in client_dirs:
        file_path = client_dir / split_file
        if not file_path.exists():
            raise FileNotFoundError(f"Missing '{split_file}' in {client_dir!s}.")

        targets = _load_targets(file_path)
        if targets.size == 0:
            raise ValueError(
                f"Found zero targets in {file_path!s}; cannot create plot."
            )

        max_label = max(max_label, int(targets.max()))
        counts.append(targets)

    if num_classes is None:
        num_classes = max_label + 1
    elif num_classes <= max_label:
        raise ValueError(
            "Provided 'num_classes' is not compatible with the observed labels."
        )

    histogram = np.zeros((len(counts), num_classes), dtype=int)
    for idx, targets in enumerate(counts):
        histogram[idx] = np.bincount(targets, minlength=num_classes)

    client_names = [client_dir.name for client_dir in client_dirs]
    return client_names, histogram


def _format_class_labels(num_classes: int) -> list[str]:
    return [f"Class {idx}" for idx in range(num_classes)]


def plot_distributions(
    client_names: Sequence[str],
    class_counts: np.ndarray,
    *,
    output_path: Path,
) -> None:
    """Create count and proportion heatmaps for ``class_counts``."""

    num_clients, num_classes = class_counts.shape
    class_labels = _format_class_labels(num_classes)

    proportions = class_counts / class_counts.sum(axis=1, keepdims=True)

    fig, axes = plt.subplots(1, 2, figsize=(max(8.0, num_clients * 0.5), 8))

    heatmaps = [
        (class_counts, axes[0], "Sample counts"),
        (proportions, axes[1], "Per-client proportions"),
    ]

    for data, axis, title in heatmaps:
        mesh = axis.imshow(data, aspect="auto", cmap="viridis")
        axis.set_yticks(range(num_clients), client_names)
        axis.set_title(title)
        axis.set_xlabel("Class")
        axis.set_ylabel("Client")
        fig.colorbar(mesh, ax=axis, fraction=0.046, pad=0.04)

    fig.suptitle("CIFAR-10 LDA partition class distribution", fontsize=16)
    fig.tight_layout(rect=(0, 0.03, 1, 0.95))

    output_path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(output_path, dpi=300)
    plt.close(fig)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Visualise client class distributions for CIFAR-10 partitions.",
    )
    parser.add_argument(
        "--partition-dir",
        type=Path,
        default=Path("/data/CIFAR10/lda_0.5_10"),
        help="Path to the partition directory to be analysed.",
    )
    parser.add_argument(
        "--split",
        choices=("train", "test"),
        default="train",
        help="Dataset split to load from each client directory.",
    )
    parser.add_argument(
        "--num-classes",
        type=int,
        default=None,
        help="Force a specific number of classes for the resulting histogram.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("plotting/plots/data/cifar10_lda_distribution.png"),
        help="Location where the generated figure will be stored.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    client_names, histogram = load_class_counts(
        args.partition_dir, split=args.split, num_classes=args.num_classes
    )
    plot_distributions(client_names, histogram, output_path=args.output)


if __name__ == "__main__":
    main()
